#!/usr/bin/python3

import subprocess as sp
import argparse
import os
import time

res=0
uid=""

def check_if_has(lines,itms):
    """check_if_has checks to see if any item in itms is in the lines"""
    for x in itms:
        for l in lines:
            if x in l:
                print(l)
                return True
    return False

trailers="\n\r\t "

def runecho(args,timeout=10.0):
    p1=sp.Popen(args,stderr=sp.STDOUT,stdout=sp.PIPE,encoding="utf-8")
    tstart=time.time()
    rv=[]
    cline=""
    while True:
        oc=p1.stdout.read(1)
        if not oc:
            time.sleep(0.10)
            if p1.poll()!=None:
                if len(cline)>0:
                   rv.append(cline)
                return rv
            if (time.time()-tstart)>timeout :
                p1.kill()
                if len(cline)>0:
                   rv.append(cline)
                print("Timeout")
                rv.append("Timeout")
                return rv
        else:
           print(oc,end="")
           if oc=="\n":
               rv.append(cline)
               cline=""
           else:
               cline+=oc
    if len(cline)>0:
       rv.append(cline)
    return rv


def runsynthesis(clkperiod):
    simres="No returned result\n"
    try:
        os.remove("synthesis.script")
    except:
        pass
    with open("synthesis.script","w") as fs:
        fs.write("""set link_library {{/apps/toshiba/sjsu/synopsys/tc240c/tc240c.db_NOMIN25 /apps/synopsys/PrimeTimeNew/pts/Q-2019.12/libraries/syn/dw_foundation.sldb}}
set target_library {{/apps/toshiba/sjsu/synopsys/tc240c/tc240c.db_NOMIN25}}
suppress_message {{ UID-401 VER-130 }}
read_sverilog "vid5a.sv"
current_design vid5a
create_clock clk -name clk -period {1:5.3f}
set_propagated_clock clk
set_clock_uncertainty 0.25 clk
set_propagated_clock clk
set_output_delay 0.5 -clock clk [all_outputs]
set all_inputs_wo_rst_clk [remove_from_collection [remove_from_collection [all_inputs] [get_port clk]] [get_port reset]]
set_driving_cell -lib_cell CND2X1 $all_inputs_wo_rst_clk
set_input_delay 0.6 -clock clk $all_inputs_wo_rst_clk
set_output_delay 0.6 -clock clk [all_outputs]
set_fix_hold [ get_clocks clk ]
set_output_delay 0.3 -clock clk [all_outputs]
set_max_delay {1:5.3f} -from [all_inputs] -to [all_outputs]
compile_ultra
create_clock clk -name clk -period {0:5.3f}

update_timing
report_timing -max_paths 5
write -hierarchy -format verilog -output vid5a_gates.v
quit

""".format(clkperiod,clkperiod*0.7))
    try:
        os.remove("vid5a_gates.v")
    except:
        pass
    try:
        arg=["/home/morris/287/sss"]
        simres=runecho(arg,timeout=600)
    except:
        print("Synthesis didn't work")
        print(simres)
        res.write("synthesis didn't run\n")
        return False
    lines=simres
    if check_if_has(lines,["Latch","latch","Error","error","timing arc",
                           "violated","Violated"]):
        print("Synthesis has errors")
        res.write("Synthesis failed\n")
        return False
    else:
        print("Synthesis seems to have worked")
        res.write("Synthesis seemed to work")
        return True

def runvcs():
    sp.call(["rm","-rf","simv","simv.daidir","csrc","*.vcd"])
    simres="No returned result\n"
    try:
        arg=["./sv_uvm","top.sv"]
        simres=runecho(arg,timeout=15)
    except:
        print("Simulation didn't work")
        print(simres)
        res.write("VCS didn't run\n")
        return False
    lines=simres
    if not check_if_has(lines,["[Passed :-)]     1"]):
        print("VCS simulation didn't complete successfully")
        res.write("VCS didn't complete successfully\n")
        return False
    res.write("VCS simulation ran\n")
    print("\n\n\nVCS simulation worked\n\n")
    return True



def runncgates():
    sp.call(["rm","-rf","simv","simv.daidir","csrc","*.vcd","INCA_libs",
             "ncverilog.log","ncverilog.history"])
    simres="No returned result\n"
    try:
        arg=["/home/morris/287/sv_ncgates","top_gates.svp"]
        simres=runecho(arg,timeout=100)
    except:
        print("Simulation didn't work")
        print(simres)
        res.write("ncverilog gates didn't run\n")
        return False
    lines=simres
    if not check_if_has(lines,["The Gates worked --- Have a nice day"]):
        print("ncverilog gates simulation didn't complete successfully")
        res.write("ncverilog gates didn't complete successfully\n")
        return False
    res.write("ncverilog gates simulation ran\n")
    print("\n\n\nncverilog gates simulation worked\n\n")
    return True


def main():
    global res,uid
    clkperiod=40.0
    resfn="results.txt"
    parser=argparse.ArgumentParser(description='272 HW synthesis')
    parser.add_argument("--clkperiod",default=5.0)
    parser.add_argument("--resultsFileName",default="results.txt")
    parser.add_argument("--rootname",default="vid5a")
    parser.add_argument("--filename",default="vid5a.sv")
    args = parser.parse_args()
    print(args)
    resfn=args.resultsFileName
    clkperiod=float(args.clkperiod)
    filename=args.filename
    with open(resfn,"w") as res:
        uid=runecho(['id','-un'])
        res.write("HW1 run for user {}\n".format(uid))
        res.write("Run at {}\n".format(time.asctime(time.localtime(time.time()))))
        if not runvcs():
            return
        if not runsynthesis(clkperiod):
            return
        if not runncgates():
            return
        res.write("HW1 synthesis worked\n")

main()

